# 공통 환경
spring:
  profiles:    active: local

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

#properties 파일에선..      
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#server:
#  undertow:
#    accesslog: 
#      dir: # Undertow access log directory.
#      enabled: false # Whether to enable the access log.
#      pattern: common # Format pattern for access logs.
#      prefix: access_log. # Log file name prefix.
#      rotate: true # Whether to enable access log rotation.
#      suffix: log # Log file name suffix.
#    buffer-size: # Size of each buffer, in bytes.
##    direct-buffers: # Whether to allocate buffers outside the Java heap.
##    io-threads: # Number of I/O threads to create for the worker.
#    eager-filter-init: true # Whether servlet filters should be initialized on startup.
#    max-http-post-size: 0 # Maximum size, in bytes, of the HTTP post content.
##    worker-threads: # Number of worker threads.
